### ISSUE TITLE
Error when trying to run denode

### ISSUE THREAD

**Issue by figalex** [steelbrain/denode#24]
I was just trying denode for the first time and this is what I got:

/usr/local/lib/node_modules/denode/node_modules/electron-localshortcut/index.js:118
app.on('browser-window-focus', (e, win) => {
   ^

TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/denode/node_modules/electron-localshortcut/index.js:118:4)
    at Object.<anonymous> (/usr/local/lib/node_modules/denode/node_modules/electron-localshortcut/index.js:151:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/denode/node_modules/electron-debug/index.js:3:23)

**Comment by steelbrain** [comment]
That's unusual, bug in deep dependency, will investigate
